name: interesting-category
description: Validate that the next draft release is interesting
inputs:
  GITHUB_TOKEN:
    description: Token to run with, defaults to the repository GITHUB_TOKEN
    required: true
  INTERESTING_CATEGORIES:
    required: true
    description: |
      Regexp of emojis from https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml representing changes of interest to users.
      By default excludes 📦📝👻🚦 under the assumption these do not normally merit a release.
      An output of interesting = true/false will be set, the 'workflow_dispatch' (explicit release) is always 'interesting'.
    default: '[💥🚨🎉🐛⚠🚀🌐👷]|:(boom|tada|construction_worker):'
outputs:
  interesting:
    description: whether the category is interesting or not, true / false will be the result
    value: ${{ steps.interesting-category.outputs.interesting }}
runs:
  using: composite
  steps: 
    - run: GITHUB_TOKEN=${{ inputs.GITHUB_TOKEN }} INTERESTING_CATEGORIES='${{ inputs.INTERESTING_CATEGORIES }}' $GITHUB_ACTION_PATH/run.sh
      id: interesting-category
      shell: bash
